apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-deployment
spec:
  template:
    spec:
      containers:
        - name: catalogue-container
          env:
            - name: APP_VERSION
              value: "1.0"
