# Database Configurations (Default to H2 In-Memory for self-contained execution)
spring.datasource.url=${DB_URL:jdbc:h2:mem:productdb;DB_CLOSE_DELAY=-1}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.properties.hibernate.dialect=${DB_DIALECT:org.hibernate.dialect.H2Dialect}

# JPA/Hibernate parameters
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Application parameters
server.port=${PORT:9191}
app.version=${APP_VERSION:1.0}
