apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalogue-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: catalogue-pod-role
rules:
  # Minimally scoped RBAC read permissions
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: catalogue-pod-rolebinding
subjects:
  - kind: ServiceAccount
    name: catalogue-service-account
roleRef:
  kind: Role
  name: catalogue-pod-role
  apiGroup: rbac.authorization.k8s.io
